# DO NOT CHANGE THE CODE BELOW
before_install:
  - R -q -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
  - R -q -e 'if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE


# Custom parts:

# Header
language: r
sudo: false
dist: xenial
cache: packages
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip
latex: true
pandoc_version: 2.5

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - BUILD_PKGDOWN=true
  - _R_CHECK_TESTS_NLINES_=0

matrix:
  include:
    - name: "Backend: TensorFlow | Implementation: Keras"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Backend: TensorFlow | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Backend: TensorFlow Eager | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.12"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.12.3"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.13"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.13.2"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 2.0.0"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="2.0.0"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.14"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.14"
    - name: "Backend: Tensorflow | Implementation: TensorFlow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "Backend: Tensorflow Eager | Implementation: Tensorflow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (release version) with reticulate master"
      env:
        - TENSORFLOW_VERSION="1.14"
      r_github_packages:
        - rstudio/reticulate
    - name: "TensorFlow (nightly) with reticulate master"
      env:
        - TENSORFLOW_VERSION="nightly"
      r_github_packages:
        - rstudio/reticulate
  allow_failures:
    - name: "Backend: Tensorflow | Implementation: TensorFlow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "Backend: Tensorflow Eager | Implementation: Tensorflow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Backend: TensorFlow Eager | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (nightly) with reticulate master"
      env:
        - TENSORFLOW_VERSION="nightly"
      r_github_packages:
        - rstudio/reticulate

before_script:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'keras::install_keras(tensorflow = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = "IPython")'
  - R -e 'tensorflow::tf_config()'
  
after_failure:
  - Rscript -e 'library(keras); testthat::test_dir("tests/testthat/")'